// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCns-Xr61TnOBZU1QKpzYLyx0sTEGUdGw4',
    appId: '1:131126057606:web:028cee45c440361157cf07',
    messagingSenderId: '131126057606',
    projectId: 'aryavart-f7706',
    authDomain: 'aryavart-f7706.firebaseapp.com',
    storageBucket: 'aryavart-f7706.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkZQLa9p3m3RCufzPaFn0JlAhqaNnA_b8',
    appId: '1:131126057606:android:c4641f75c3a7884057cf07',
    messagingSenderId: '131126057606',
    projectId: 'aryavart-f7706',
    storageBucket: 'aryavart-f7706.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1QPp-Tzk7DimJsjWOgJhscz16OIw1arM',
    appId: '1:131126057606:ios:f9384b8467ae7ac957cf07',
    messagingSenderId: '131126057606',
    projectId: 'aryavart-f7706',
    storageBucket: 'aryavart-f7706.appspot.com',
    iosClientId: '131126057606-efrtn5abqf1eqktasgn18egiac27nos1.apps.googleusercontent.com',
    iosBundleId: 'com.example.aryavarta',
  );
}
